services:
  dominoes-test-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        START_SCRIPT: start:test
    container_name: dominoes-test-backend
    restart: unless-stopped
    networks:
      - web

  dominoes-prod-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        START_SCRIPT: start:prod
    container_name: dominoes-prod-backend
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true